services:
  - type: web
    name: context-aware-bot
    env: python
    plan: free
    runtime: python-3.12.0
    buildCommand: pip install -r requirements.txt
    startCommand: sh ./start.sh
    autoDeploy: true
